### ISSUE TITLE
404: Page not found at page "Send a Transaction"

### ISSUE THREAD

**Issue by lansehuiyi6** [wandevs/wandevs.org#1]
When i click the link "Send a Transaction", the follow shows  404: Page not found
Sorry, we've misplaced that URL or it's pointing to something that doesn't exist. Head back home to try finding it again

**Comment by jsgoyette** [comment]
Thanks for submitting the issue. The site is still under construction, and so yes, there are several pages that are still missing. As they get filled in the 404's will get resolved. Our timeline is to have all the pages completed by March 8 or so.

Also, to make it more clear that the site is still under construction I added a notice to the top navbar.
